accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

# 이 코드로 {% url 'accounts:~' %} 사용 가능
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

mall/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('search/<str:q>/', views.ProductSearch.as_view()),
    path('update_product/<int:pk>/', views.ProductUpdate.as_view()),
    path('create_product/', views.ProductCreate.as_view()),
    path('category/<str:slug>', views.category_page),   # 서버IP/mall/category/slug
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.ProductDetail.as_view()),
    path('', views.ProductList.as_view()),
    path('mypage/', views.myPage)
]

myShopping/urls.py
from django.contrib import admin
from django.urls import path, include

# 미디어 파일을 위한 url 지정하기
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('mall/', include('mall.urls')),    # 서버IP/mall
    path('admin/', admin.site.urls),        # 서버IP/admin
    path('', include('single_pages.urls')),  # 서버IP/
    path('accounts/', include('allauth.urls')),
    path('markdownx/', include('markdownx.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # 서버IP/media/

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="E-MAIL")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

    '''
    # 오류 메시지 customization
    def clean(self):
        # 비밀번호가 6자리 이하일 때
        #username = self.cleaned_data["username"]
        password1 = self.cleaned_data['password1']
        #password2 = self.cleaned_data['password2']

        if len(password1) <= 8:
            raise forms.ValidationError("비밀번호는 8자리 이상이어야 합니다.")
        return password1

        #elif User.objects.filter(username).exists():
            #raise forms.ValidationError("이미 회원가입한 사용자입니다. 다른 아이디로 시도해주십시오.")

        #elif password1 != password2:
            #raise forms.ValidationError("비밀번호가 일치하지 않습니다. 다시 입력해주십시오.")
    '''

accounts/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from accounts.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # 입력한 정보 검증, 신규 사용자 생성
            user = authenticate(username=username, password=raw_password)
            # 자동 로그인
            login(request, user)
            return redirect('/')
    # GET 요청인 경우에는 회원가입 화면을 리턴
    else:
        form = UserForm()
    return render(request, 'accounts/sign_up.html', {'form': form})

# UserCreationForm의 is_valid 함수는 계정생성 화면의 필드값 3개가 모두 입력되었는지,
# 비밀번호1과 비밀번호2가 같은지,
# 비밀번호의 값이 비밀번호 생성 규칙에 맞는지 등을 검사한다.


'''
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth  # 계정에 대한 권한

# 회원가입 기능
def signup(request):
    # POST 요청이 왔을 때, 입력한 두 비밀번호가 같으면 새로운 USER 생성
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                                            username=request.POST['username'],
                                            password=request.POST['password1'],
                                            email=request.POST['email'],
                                            )
            # 소셜로그인으로 가져온 정보를 다른 곳에 저장한다면 맨 뒤의 ModelBackend 부분을 수정
            auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            # auth.login(request, user)  # 새 USER 생성하면 자동 로그인
            return redirect('/')
        else:  # 비밀번호 2개가 같지 않으면
            return render(request, 'accounts/signup.html')  # {% url 'signup' %}

    # signup으로 GET 요청이 왔을 때, 회원가입 화면을 띄워준다.
    return render(request, 'accounts/signup.html')
'''

'''
    form = UserCreationForm
    return render(request, 'signup.html', {'form':form})
'''


'''
# 로그인
def login(request):
    # login으로 POST 요청이 들어왔을 때, 로그인 한다.
    if request.method == "POST":
        # login.html에서 넘어온 username과 password를 각 변수에 저장한다.
        username = request.POST["username"]
        password = request.POST["password"]

        # 해당 username과 password와 일치하는 user 객체를 가져온다.
        user = auth.authenticate(request, username=username, password=password)

        # 해당 user 객체가 존재한다면
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:  # 존재X => 딕셔너리에 에러메세지를 전달하고 다시 login.html 화면으로 돌아간다.
            return render(request, 'accounts/login.html')

    else:  # login으로 GET 요청이 들어왔을때, 로그인 화면을 띄워준다.
        return render(request, 'accounts/login.html')


# 로그아웃
def logout(request):
    # logout으로 POST 요청이 들어왔을 때, 로그아웃한다.
    if request.method == 'POST':
        auth.logout(request)
        return redirect('/')
    # logout으로 GET 요청이 들어왔을 때, 로그인 화면을 띄워준다.
    return render(request, 'login.html')
'''

accounts/templates/accounts/form_errors.html
<!-- 로그인/회원가입 실패 시 실패한 이유 피드백 -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력: 값 누락, 필드 형식 불일치 -->
            <div class="alert alert-danger">
                {% if "This field" in error %}
                    <strong>{{ field.label }} is required</strong>
                {% else %}
                    <strong>{{ error | escape }}</strong>
                {% endif %}
                <!--  {{ form.errors.as_data }}  {{ field.label }} is required-->
            </div>
        {% endfor %}
    {% endfor %}

    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력: 로그인 실패 시 -->
        <div class="alert alert-danger">
                {% if "This field" in error %}
                    <strong>{{ field.label }} is required</strong>
                {% else %}
                    <strong>{{ error | escape }}</strong>
                {% endif %}
                <!--  {{ form.errors.as_data }}  {{ field.label }} is required-->
            </div>
    {% endfor %}
{% endif %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}" media="screen">
    </head>

    <body>
        <div id="con">
        <div id="login">
        <div id="login_form"><!--로그인 폼-->

            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "accounts/form_errors.html" %}
                <h3 class="login" style="letter-spacing:-1px;">LOG IN</h3>
                <hr>

                <div class="form-group">
                    <p style="text-align: left; font-size:15px; color:#666">
                        <label for="username">USERNAME</label>
                    </p>
                    <input type="text" class="form-control size" name="username" id="username"
                           value="{{ form.username.value|default_if_none:'' }}" placeholder="아이디">
                </div>

                <div class="form-group">
                    <p style="text-align: left; font-size:15px; color:#666">
                        <label for="password">Password</label>
                    </p>
                    <input type="password" class="form-control size" name="password" id="password"
                       value="{{ form.password.value|default_if_none:'' }}" placeholder="비밀번호">
                </div>
                <br/>
                <button type="submit" class="btn btn-outline-primary">LOG IN</button>
            </form>

            <hr>
            <p class="find"><span>아직 회원이 아니세요?  <a href="{% url 'accounts:signup' %}">Go to SIGN UP!</a></span>
        </div>
        </div>
        </div>
    </body>
</html>

accounts/templates/accounts/sign_up.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}

<html lang="ko">
    <head>
        <link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}" media="screen">
    </head>

    <body>
        <div id="con">
        <div id="login">
        <div id="login_form"><!--로그인 폼-->

            <form method="post" class="post-form">
                {% csrf_token %}
                {% include "accounts/form_errors.html" %}
                <h3 class="login" style="letter-spacing:-1px;">SIGN UP</h3>
                <hr>
                <div class="form-group">
                    <p style="text-align: center; font-size:10px; color:#333">
                        다른 서비스로 회원가입
                    </p>
                    <a class="btn btn-outline-dark" href="{% provider_login_url 'google' %}">
                        <i class="fab fa-google"></i>
                    </a>
                </div>
                <hr>
                <div class="form-group">
                    <p style="text-align: left; font-size:15px; color:#666">
                        <label for="username">USERNAME</label>
                    </p>
                    <input type="text" class="form-control size" name="username" id="username"
                           value="{{ form.username.value|default_if_none:'' }}" placeholder="아이디">
                </div>

                <div class="form-group">
                    <p style="text-align: left; font-size:15px; color:#666">
                        <label for="password1">PASSWORD</label>
                    </p>
                    <input type="password" class="form-control size" name="password1" id="password1"
                           value="{{ form.password1.value|default_if_none:'' }}" placeholder="영문,숫자 포함 8자 이상 비밀번호">
                </div>

                <div class="form-group">
                    <p style="text-align: left; font-size:15px; color:#666">
                        <label for="password2">PASSWORD AGAIN</label>
                    </p>
                    <input type="password" class="form-control size" name="password2" id="password2"
                           value="{{ form.password2.value|default_if_none:'' }}" placeholder="비밀번호 확인">
                </div>

                <div class="form-group">
                    <p style="text-align: left; font-size:15px; color:#666">
                        <label for="email">E-MAIL</label>
                    </p>
                    <input type="text" class="form-control size" name="email" id="email"
                           value="{{ form.email.value|default_if_none:'' }}" placeholder="이메일">
                </div>
                <br/>
                <button type="submit" class="btn btn-outline-primary">SIGN UP</button>
            </form>
            <hr>
            <p class="find"><span>회원이신가요?  <a href="{% url 'accounts:login' %}">Go to LOG-IN!</a></span></p>
        </div>
        </div>
        </div>
    </body>
</html>